// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixpegnrmifyktyrtkkzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4cGVnbnJtaWZ5a3R5cnRra3p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1OTUxMDUsImV4cCI6MjA2MDE3MTEwNX0.3QY9JiozmA1aR5sdo81W6DPXmvIJOLxfQo1DPpo9EMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);